version: '2'
services:
    jhipster5-app:
        image: jhipster5
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipster5-mysql:3306/jhipster5?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipster5-elasticsearch:9300
        ports:
            - 8080:8080
    jhipster5-mysql:
        extends:
            file: mysql.yml
            service: jhipster5-mysql
    jhipster5-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipster5-elasticsearch
